name: dart_builder_ip
description: >- 
  Simplifies connecting Flutter apps to local emulators (e.g., Firebase Emulators) 
  by providing a build-time constant with the builder's IP address.
version: 1.0.0
repository: https://github.com/olostan/dart_builder_ip

environment:
  sdk: '>=3.4.3 <4.0.0'

# Add regular dependencies here.
dependencies:
  source_gen: ^1.5.0
  build: ^2.4.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13

